// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMslg1t1hDDOVjz82hWM55komV0luP6RQ',
    appId: '1:652996441261:web:18c12383b955cf9cb00224',
    messagingSenderId: '652996441261',
    projectId: 'content-hub-yan-2026',
    authDomain: 'content-hub-yan-2026.firebaseapp.com',
    storageBucket: 'content-hub-yan-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Y0lH5-QxdiVfLPfIIGXrkFte77CH1DY',
    appId: '1:652996441261:android:c45e708048371c95b00224',
    messagingSenderId: '652996441261',
    projectId: 'content-hub-yan-2026',
    storageBucket: 'content-hub-yan-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg9099acgl2fu2OcUWVDh52rZoPbYnFEw',
    appId: '1:652996441261:ios:befe69ab54578a5fb00224',
    messagingSenderId: '652996441261',
    projectId: 'content-hub-yan-2026',
    storageBucket: 'content-hub-yan-2026.firebasestorage.app',
    iosBundleId: 'com.example.contentHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg9099acgl2fu2OcUWVDh52rZoPbYnFEw',
    appId: '1:652996441261:ios:befe69ab54578a5fb00224',
    messagingSenderId: '652996441261',
    projectId: 'content-hub-yan-2026',
    storageBucket: 'content-hub-yan-2026.firebasestorage.app',
    iosBundleId: 'com.example.contentHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMslg1t1hDDOVjz82hWM55komV0luP6RQ',
    appId: '1:652996441261:web:ee711d2aeef037b0b00224',
    messagingSenderId: '652996441261',
    projectId: 'content-hub-yan-2026',
    authDomain: 'content-hub-yan-2026.firebaseapp.com',
    storageBucket: 'content-hub-yan-2026.firebasestorage.app',
  );
}
